export const phone = '(max-width: 599px)'
export const tabletPortrait = '(min-width: 600px)'
export const tabletLandscape = '(min-width: 900px)'
export const desktop = '(min-width: 1200px)'
export const retina = '(min-width: 1800px)'
