query getBandBySlug($slug: String!) {
  getBandBySlug(slug: $slug) {
    id
    name
    bio
    slug
    photos {
      id
      src
      width
      height
    }
    similarBands {
      name
      bio
      slug
    }
    albums {
      id
      cover
      title
      year
      songs {
        id
        audio
        length
        title
        trackNumber
      }
    }
  }
}
