query getBandBySlug($slug: String!) {
  getBandBySlug(slug: $slug) {
    id
    name
    bio
    photos {
      id
      src
      width
      height
    }
    albums {
      cover
      title
      year
      songs {
        id
        audio
        length
        title
      }
    }
  }
}
